### ISSUE TITLE
Decoding JWT doesn't work

### ISSUE THREAD

**Issue by bluengreen** [jcolemorrison/redux-sagas-authentication-app#4]
Can you describe how this bit of code works? 

https://github.com/jcolemorrison/redux-sagas-authentication-app/blob/master/src/lib/check-auth.js#L14-L17

The way I'm reading this is that it won't work. `token.created` isn't returning from the token. I've verified in the console. So the result is if the token has expired the server returns a 401 from the API calls, but based on this bit of code it thinks its all good. I suspect this is suppose to force you to login again if the token from localStorage is expired. 

Thanks

**Comment by bluengreen** [comment]
Ok after taking some time to resolve this, this is what I ended up with to check the expiration of the token from localStorage. I'm using react router v4 so I return true false rather than passing to next state. 

```
const parseJwt = (token) => {
  var base64Url = token.split('.')[1];
  var base64 = base64Url.replace('-', '+').replace('_', '/');
  return JSON.parse(window.atob(base64));
}

const checkAuthorization = (dispatch) => {
  // attempt to grab the token from localstorage
  const storedToken = localStorage.getItem('token')

  // if it exists
  if (storedToken) {

    // parse it down into an object
    const token = JSON.parse(storedToken)
    const tokenPayload = parseJwt(token.jwt)

    // check the expiration against the current date / time
    const expiration = new Date(tokenPayload.exp*1000)
    const current = new Date().getTime()

    // if the token has expired return false
    if (current > expiration) return false

    // otherwise, dispatch the token to our setClient action
    // which will update our redux state with the token and return true
    dispatch(setUser(token))
    return true
  }

  return false
}
```

**Comment by jcolemorrison** [comment]
Hey @bluengreen nice.  Sorry for the delayed response.

And yeah, you're right, it was to force expiration.

This is great stuff, thanks for the input!
